// This file was automatically generated by Typical 0.0.0.
// Visit https://github.com/stepchowfun/typical for more information.

/* eslint-disable */

import {
  Deserializable,
  dataViewFromDeserializable,
  deserializeFieldHeader,
  deserializeVarint,
  fieldHeaderSize,
  missingFieldsErrorMessage,
  serializeFieldHeader,
  serializeVarint,
  textDecoder,
  textEncoder,
  unreachable,
  varintSizeFromValue,
  zigzagDecode,
  zigzagEncode,
} from '../common';

import * as _Types from './dependency/types';

export type StructFromAboveAtlas = {
  $size: number;
  field: Uint8Array;
  size: Uint8Array;
  elements: Uint8Array;
  fallback: Uint8Array;
};

export type StructFromAboveOut = {
  field: string;
  size: string;
  elements: string;
  fallback: string;
};

export type StructFromAboveIn = {
  field: string;
  size: string;
  elements: string;
  fallback: string;
};

function structFromAboveAtlas(message: StructFromAboveOut): StructFromAboveAtlas {
  let size = 0;

  let $field: Uint8Array;
  let $size: Uint8Array;
  let $elements: Uint8Array;
  let $fallback: Uint8Array;

  {
    let payloadAtlas: Uint8Array;
    const payload = message.field;
    payloadAtlas = textEncoder.encode(payload);
    $field = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(0n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas: Uint8Array;
    const payload = message.size;
    payloadAtlas = textEncoder.encode(payload);
    $size = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(1n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas: Uint8Array;
    const payload = message.elements;
    payloadAtlas = textEncoder.encode(payload);
    $elements = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(2n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas: Uint8Array;
    const payload = message.fallback;
    payloadAtlas = textEncoder.encode(payload);
    $fallback = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(3n, payloadSize, false) + payloadSize;
  }

  return {
    $size: size,
    field: $field,
    size: $size,
    elements: $elements,
    fallback: $fallback,
  };
}

function structFromAboveSize(message: StructFromAboveOut): number {
  return structFromAboveAtlas(message).$size;
}

function structFromAboveSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: StructFromAboveOut,
  atlas: StructFromAboveAtlas,
): number {
  {
    const payload = message.field;
    const payloadAtlas = atlas.field;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 0n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer as ArrayBuffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.size;
    const payloadAtlas = atlas.size;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 1n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer as ArrayBuffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.elements;
    const payloadAtlas = atlas.elements;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 2n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer as ArrayBuffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.fallback;
    const payloadAtlas = atlas.fallback;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 3n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer as ArrayBuffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  return offset;
}

function structFromAboveDeserializeUnsafe(dataView: DataView): StructFromAboveIn {
  const dataViewAlias = dataView;

  let offset = 0;

  let $field: string | undefined;
  let $size: string | undefined;
  let $elements: string | undefined;
  let $fallback: string | undefined;

  while (true) {
    let index: bigint;
    let payloadSize: number;

    try {
      [offset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    } catch (e) {
      if (e instanceof RangeError) {
        break;
      } else {
        throw e;
      }
    }

    switch (index) {
      case 0n: {
        const dataView = new DataView(
          dataViewAlias.buffer as ArrayBuffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new DataView(
            dataView.buffer as ArrayBuffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $field = payload;
        break;
      }
      case 1n: {
        const dataView = new DataView(
          dataViewAlias.buffer as ArrayBuffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new DataView(
            dataView.buffer as ArrayBuffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $size = payload;
        break;
      }
      case 2n: {
        const dataView = new DataView(
          dataViewAlias.buffer as ArrayBuffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new DataView(
            dataView.buffer as ArrayBuffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $elements = payload;
        break;
      }
      case 3n: {
        const dataView = new DataView(
          dataViewAlias.buffer as ArrayBuffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new DataView(
            dataView.buffer as ArrayBuffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $fallback = payload;
        break;
      }
      default:
        offset += payloadSize;
        break;
    }
  }

  if ($field === undefined
    || $size === undefined
    || $elements === undefined
    || $fallback === undefined) {
    throw new Error(missingFieldsErrorMessage);
  }

  return {
    field: $field,
    size: $size,
    elements: $elements,
    fallback: $fallback,
  };
}

function structFromAboveSerialize(message: StructFromAboveOut): ArrayBuffer {
  const atlasValue = structFromAboveAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  structFromAboveSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function structFromAboveDeserialize(bytes: Deserializable): StructFromAboveIn | Error {
  try {
    return structFromAboveDeserializeUnsafe(dataViewFromDeserializable(bytes));
  } catch (e) {
    return e as Error;
  }
}

export const StructFromAbove = {
  atlas: structFromAboveAtlas,
  size: structFromAboveSize,
  serializeWithAtlasUnsafe: structFromAboveSerializeWithAtlasUnsafe,
  deserializeUnsafe: structFromAboveDeserializeUnsafe,
  serialize: structFromAboveSerialize,
  deserialize: structFromAboveDeserialize,
};
