// This file was automatically generated by Typical 0.0.0.
// Visit https://github.com/stepchowfun/typical for more information.

/* eslint-disable */

import {
  Deserializable,
  dataViewFromDeserializable,
  deserializeFieldHeader,
  deserializeVarint,
  fieldHeaderSize,
  missingFieldsErrorMessage,
  serializeFieldHeader,
  serializeVarint,
  textDecoder,
  textEncoder,
  unreachable,
  varintSizeFromValue,
  zigzagDecode,
  zigzagEncode,
} from '../common';

export type EmptyStructAtlas = {
  $size: number;
};

export type EmptyStructOut = {
};

export type EmptyStructIn = {
};

function emptyStructAtlas(message: EmptyStructOut): EmptyStructAtlas {
  let size = 0;

  return {
    $size: size,
  };
}

function emptyStructSize(message: EmptyStructOut): number {
  return 0;
}

function emptyStructSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: EmptyStructOut,
  atlas: EmptyStructAtlas,
): number {
  return offset;
}

function emptyStructDeserializeUnsafe(dataView: DataView): EmptyStructIn {
  const dataViewAlias = dataView;

  let offset = 0;

  while (true) {
    let index: bigint;
    let payloadSize: number;

    try {
      [offset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    } catch (e) {
      if (e instanceof RangeError) {
        break;
      } else {
        throw e;
      }
    }

    switch (index) {
      default:
        offset += payloadSize;
        break;
    }
  }

  return {
  };
}

function emptyStructSerialize(message: EmptyStructOut): ArrayBuffer {
  const atlasValue = emptyStructAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  emptyStructSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function emptyStructDeserialize(bytes: Deserializable): EmptyStructIn | Error {
  try {
    return emptyStructDeserializeUnsafe(dataViewFromDeserializable(bytes));
  } catch (e) {
    return e as Error;
  }
}

export const EmptyStruct = {
  atlas: emptyStructAtlas,
  size: emptyStructSize,
  serializeWithAtlasUnsafe: emptyStructSerializeWithAtlasUnsafe,
  deserializeUnsafe: emptyStructDeserializeUnsafe,
  serialize: emptyStructSerialize,
  deserialize: emptyStructDeserialize,
};

export type EmptyChoiceAtlas = never;

export type EmptyChoiceOut = never;

export type EmptyChoiceIn = never;

function emptyChoiceAtlas(message: EmptyChoiceOut): EmptyChoiceAtlas {
  return unreachable(message);
}

function emptyChoiceSize(message: EmptyChoiceOut): number {
  return 0;
}

function emptyChoiceSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: EmptyChoiceOut,
  atlas: EmptyChoiceAtlas,
): number {
  return unreachable(message);
}

function emptyChoiceDeserializeUnsafe(dataView: DataView): EmptyChoiceIn {
  const dataViewAlias = dataView;

  let offset = 0;

  while (true) {
    const [newOffset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    offset = newOffset;

    switch (index) {
      default:
        offset += payloadSize;
        break;
    }
  }
}

function emptyChoiceSerialize(message: EmptyChoiceOut): ArrayBuffer {
  return unreachable(message);
}

function emptyChoiceDeserialize(bytes: Deserializable): EmptyChoiceIn | Error {
  try {
    return emptyChoiceDeserializeUnsafe(dataViewFromDeserializable(bytes));
  } catch (e) {
    return e as Error;
  }
}

export const EmptyChoice = {
  atlas: emptyChoiceAtlas,
  size: emptyChoiceSize,
  serializeWithAtlasUnsafe: emptyChoiceSerializeWithAtlasUnsafe,
  deserializeUnsafe: emptyChoiceDeserializeUnsafe,
  serialize: emptyChoiceSerialize,
  deserialize: emptyChoiceDeserialize,
};
