// This file was automatically generated by Typical 0.0.0.
// Visit https://github.com/stepchowfun/typical for more information.

/* eslint-disable */

import {
  Deserializable,
  dataView64,
  deserializeFieldHeader,
  deserializeVarint,
  fieldHeaderSize,
  missingFieldsErrorMessage,
  serializeFieldHeader,
  serializeVarint,
  textDecoder,
  textEncoder,
  unreachable,
  varintSizeFromFirstByte,
  varintSizeFromValue,
  zigzagDecode,
  zigzagEncode,
} from '../../common';

import * as _Types from '../types';

export type StructFromBelowAtlas = {
  $size: number;
  x: _Types.StructFromAboveAtlas;
};

export type StructFromBelowOut = {
  x: _Types.StructFromAboveOut;
};

export type StructFromBelowIn = {
  x: _Types.StructFromAboveIn;
};

function structFromBelowAtlas(message: StructFromBelowOut): StructFromBelowAtlas {
  let size = 0;

  let $x;

  {
    let payloadAtlas;
    const payload = message.x;
    payloadAtlas = _Types.StructFromAbove.atlas(payload);
    $x = payloadAtlas;
    const payloadSize = (payloadAtlas as { $size: number }).$size;
    size += fieldHeaderSize(0n, payloadSize, false) + payloadSize;
  }

  return {
    $size: size,
    x: $x,
  };
}

function structFromBelowSize(message: StructFromBelowOut): number {
  return structFromBelowAtlas(message).$size;
}

function structFromBelowSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: StructFromBelowOut,
  atlas: StructFromBelowAtlas,
): number {
  {
    const payload = message.x;
    const payloadAtlas = atlas.x;
    const payloadSize = (payloadAtlas as { $size: number }).$size;
    offset = serializeFieldHeader(dataView, offset, 0n, payloadSize, false);
    offset = _Types.StructFromAbove.serializeWithAtlasUnsafe(dataView, offset, payload, payloadAtlas);
  }

  return offset;
}

function structFromBelowDeserializeUnsafe(dataView: DataView): StructFromBelowIn {
  const dataViewAlias = dataView;

  let offset = 0;

  let $x;

  while (true) {
    let index, payloadSize;

    try {
      [offset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    } catch (e) {
      if (e instanceof RangeError) {
        break;
      } else {
        throw e;
      }
    }

    switch (index) {
      case 0n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = _Types.StructFromAbove.deserializeUnsafe(dataView);
        offset = dataView.byteLength;
        offset += oldOffset;
        $x = payload;
        break;
      }
      default:
        offset += payloadSize;
        break;
    }
  }

  if ($x === undefined) {
    throw new Error(missingFieldsErrorMessage);
  }

  return {
    x: $x,
  };
}

function structFromBelowSerialize(message: StructFromBelowOut): ArrayBuffer {
  const atlasValue = structFromBelowAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  structFromBelowSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function structFromBelowDeserialize(bytes: Deserializable): StructFromBelowIn | Error {
  try {
    if (bytes instanceof ArrayBuffer) {
      return structFromBelowDeserializeUnsafe(new DataView(bytes));
    }
    if (bytes instanceof DataView) {
      return structFromBelowDeserializeUnsafe(bytes);
    }
    return structFromBelowDeserializeUnsafe(new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength));
  } catch (e) {
    return e as Error;
  }
}

export const StructFromBelow = {
  atlas: structFromBelowAtlas,
  size: structFromBelowSize,
  serializeWithAtlasUnsafe: structFromBelowSerializeWithAtlasUnsafe,
  deserializeUnsafe: structFromBelowDeserializeUnsafe,
  serialize: structFromBelowSerialize,
  deserialize: structFromBelowDeserialize,
};
