// This file was automatically generated by Typical 0.0.0.
// Visit https://github.com/stepchowfun/typical for more information.

/* eslint-disable */

import {
  Deserializable,
  dataView64,
  deserializeFieldHeader,
  deserializeVarint,
  fieldHeaderSize,
  missingFieldsErrorMessage,
  serializeFieldHeader,
  serializeVarint,
  textDecoder,
  textEncoder,
  unreachable,
  varintSizeFromFirstByte,
  varintSizeFromValue,
  zigzagDecode,
  zigzagEncode,
} from '../common';

export type ExampleStructAtlas = {
  $size: number;
  requiredToRequired: Uint8Array;
  requiredToAsymmetric: Uint8Array;
  requiredToOptional: Uint8Array | undefined;
  asymmetricToRequired: Uint8Array;
  asymmetricToAsymmetric: Uint8Array;
  asymmetricToOptional: Uint8Array | undefined;
  optionalToRequired: Uint8Array;
  optionalToAsymmetric: Uint8Array;
  optionalToOptional: Uint8Array | undefined;
  nonexistentToAsymmetric: number;
  nonexistentToOptional: number | undefined;
};

export type ExampleStructOut = {
  requiredToRequired: string;
  requiredToAsymmetric: string;
  requiredToOptional: string | undefined;
  asymmetricToRequired: string;
  asymmetricToAsymmetric: string;
  asymmetricToOptional: string | undefined;
  optionalToRequired: string;
  optionalToAsymmetric: string;
  optionalToOptional: string | undefined;
  nonexistentToAsymmetric: null;
  nonexistentToOptional: null | undefined;
};

export type ExampleStructIn = {
  requiredToRequired: string;
  requiredToAsymmetric: string | undefined;
  requiredToOptional: string | undefined;
  asymmetricToRequired: string;
  asymmetricToAsymmetric: string | undefined;
  asymmetricToOptional: string | undefined;
  optionalToRequired: string;
  optionalToAsymmetric: string | undefined;
  optionalToOptional: string | undefined;
  nonexistentToAsymmetric: null | undefined;
  nonexistentToOptional: null | undefined;
};

function exampleStructAtlas(message: ExampleStructOut): ExampleStructAtlas {
  let size = 0;

  let $requiredToRequired, $requiredToAsymmetric, $requiredToOptional, $asymmetricToRequired, $asymmetricToAsymmetric, $asymmetricToOptional, $optionalToRequired, $optionalToAsymmetric, $optionalToOptional, $nonexistentToAsymmetric, $nonexistentToOptional;

  {
    let payloadAtlas;
    const payload = message.requiredToRequired;
    payloadAtlas = textEncoder.encode(payload);
    $requiredToRequired = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(0n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.requiredToAsymmetric;
    payloadAtlas = textEncoder.encode(payload);
    $requiredToAsymmetric = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(1n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.requiredToOptional;
    if (payload !== undefined) {
      payloadAtlas = textEncoder.encode(payload);
      $requiredToOptional = payloadAtlas;
      const payloadSize = payloadAtlas.byteLength;
      size += fieldHeaderSize(2n, payloadSize, false) + payloadSize;
    }
  }

  {
    let payloadAtlas;
    const payload = message.asymmetricToRequired;
    payloadAtlas = textEncoder.encode(payload);
    $asymmetricToRequired = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(4n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.asymmetricToAsymmetric;
    payloadAtlas = textEncoder.encode(payload);
    $asymmetricToAsymmetric = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(5n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.asymmetricToOptional;
    if (payload !== undefined) {
      payloadAtlas = textEncoder.encode(payload);
      $asymmetricToOptional = payloadAtlas;
      const payloadSize = payloadAtlas.byteLength;
      size += fieldHeaderSize(6n, payloadSize, false) + payloadSize;
    }
  }

  {
    let payloadAtlas;
    const payload = message.optionalToRequired;
    payloadAtlas = textEncoder.encode(payload);
    $optionalToRequired = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(8n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.optionalToAsymmetric;
    payloadAtlas = textEncoder.encode(payload);
    $optionalToAsymmetric = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(9n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.optionalToOptional;
    if (payload !== undefined) {
      payloadAtlas = textEncoder.encode(payload);
      $optionalToOptional = payloadAtlas;
      const payloadSize = payloadAtlas.byteLength;
      size += fieldHeaderSize(10n, payloadSize, false) + payloadSize;
    }
  }

  {
    let payloadAtlas;
    const payload = message.nonexistentToAsymmetric;
    payloadAtlas = 0;
    $nonexistentToAsymmetric = payloadAtlas;
    const payloadSize = payloadAtlas;
    size += fieldHeaderSize(13n, payloadSize, false) + payloadSize;
  }

  {
    let payloadAtlas;
    const payload = message.nonexistentToOptional;
    if (payload !== undefined) {
      payloadAtlas = 0;
      $nonexistentToOptional = payloadAtlas;
      const payloadSize = payloadAtlas;
      size += fieldHeaderSize(14n, payloadSize, false) + payloadSize;
    }
  }

  return {
    $size: size,
    requiredToRequired: $requiredToRequired,
    requiredToAsymmetric: $requiredToAsymmetric,
    requiredToOptional: $requiredToOptional,
    asymmetricToRequired: $asymmetricToRequired,
    asymmetricToAsymmetric: $asymmetricToAsymmetric,
    asymmetricToOptional: $asymmetricToOptional,
    optionalToRequired: $optionalToRequired,
    optionalToAsymmetric: $optionalToAsymmetric,
    optionalToOptional: $optionalToOptional,
    nonexistentToAsymmetric: $nonexistentToAsymmetric,
    nonexistentToOptional: $nonexistentToOptional,
  };
}

function exampleStructSize(message: ExampleStructOut): number {
  return exampleStructAtlas(message).$size;
}

function exampleStructSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: ExampleStructOut,
  atlas: ExampleStructAtlas,
): number {
  {
    const payload = message.requiredToRequired;
    const payloadAtlas = atlas.requiredToRequired;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 0n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.requiredToAsymmetric;
    const payloadAtlas = atlas.requiredToAsymmetric;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 1n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.requiredToOptional;
    const payloadAtlas = atlas.requiredToOptional;
    if (payload !== undefined && payloadAtlas !== undefined) {
      const payloadSize = payloadAtlas.byteLength;
      offset = serializeFieldHeader(dataView, offset, 2n, payloadSize, false);
      {
        const targetBuffer = new Uint8Array(
          dataView.buffer,
          dataView.byteOffset,
          dataView.byteLength,
        );
        targetBuffer.set(payloadAtlas, offset);
        offset += payloadAtlas.byteLength;
      }
    }
  }

  {
    const payload = message.asymmetricToRequired;
    const payloadAtlas = atlas.asymmetricToRequired;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 4n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.asymmetricToAsymmetric;
    const payloadAtlas = atlas.asymmetricToAsymmetric;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 5n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.asymmetricToOptional;
    const payloadAtlas = atlas.asymmetricToOptional;
    if (payload !== undefined && payloadAtlas !== undefined) {
      const payloadSize = payloadAtlas.byteLength;
      offset = serializeFieldHeader(dataView, offset, 6n, payloadSize, false);
      {
        const targetBuffer = new Uint8Array(
          dataView.buffer,
          dataView.byteOffset,
          dataView.byteLength,
        );
        targetBuffer.set(payloadAtlas, offset);
        offset += payloadAtlas.byteLength;
      }
    }
  }

  {
    const payload = message.optionalToRequired;
    const payloadAtlas = atlas.optionalToRequired;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 8n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.optionalToAsymmetric;
    const payloadAtlas = atlas.optionalToAsymmetric;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 9n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  {
    const payload = message.optionalToOptional;
    const payloadAtlas = atlas.optionalToOptional;
    if (payload !== undefined && payloadAtlas !== undefined) {
      const payloadSize = payloadAtlas.byteLength;
      offset = serializeFieldHeader(dataView, offset, 10n, payloadSize, false);
      {
        const targetBuffer = new Uint8Array(
          dataView.buffer,
          dataView.byteOffset,
          dataView.byteLength,
        );
        targetBuffer.set(payloadAtlas, offset);
        offset += payloadAtlas.byteLength;
      }
    }
  }

  {
    const payload = message.nonexistentToAsymmetric;
    const payloadAtlas = atlas.nonexistentToAsymmetric;
    const payloadSize = payloadAtlas;
    offset = serializeFieldHeader(dataView, offset, 13n, payloadSize, false);
  }

  {
    const payload = message.nonexistentToOptional;
    const payloadAtlas = atlas.nonexistentToOptional;
    if (payload !== undefined && payloadAtlas !== undefined) {
      const payloadSize = payloadAtlas;
      offset = serializeFieldHeader(dataView, offset, 14n, payloadSize, false);
    }
  }

  return offset;
}

function exampleStructDeserializeUnsafe(dataView: DataView): ExampleStructIn {
  const dataViewAlias = dataView;

  let offset = 0;

  let $requiredToRequired, $requiredToAsymmetric, $requiredToOptional, $asymmetricToRequired, $asymmetricToAsymmetric, $asymmetricToOptional, $optionalToRequired, $optionalToAsymmetric, $optionalToOptional, $nonexistentToAsymmetric, $nonexistentToOptional;

  while (true) {
    let index, payloadSize;

    try {
      [offset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    } catch (e) {
      if (e instanceof RangeError) {
        break;
      } else {
        throw e;
      }
    }

    switch (index) {
      case 0n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $requiredToRequired = payload;
        break;
      }
      case 1n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $requiredToAsymmetric = payload;
        break;
      }
      case 2n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $requiredToOptional = payload;
        break;
      }
      case 4n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $asymmetricToRequired = payload;
        break;
      }
      case 5n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $asymmetricToAsymmetric = payload;
        break;
      }
      case 6n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $asymmetricToOptional = payload;
        break;
      }
      case 8n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $optionalToRequired = payload;
        break;
      }
      case 9n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $optionalToAsymmetric = payload;
        break;
      }
      case 10n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $optionalToOptional = payload;
        break;
      }
      case 13n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = null;
        offset += oldOffset;
        $nonexistentToAsymmetric = payload;
        break;
      }
      case 14n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = null;
        offset += oldOffset;
        $nonexistentToOptional = payload;
        break;
      }
      default:
        offset += payloadSize;
        break;
    }
  }

  if ($requiredToRequired === undefined
    || $asymmetricToRequired === undefined
    || $optionalToRequired === undefined) {
    throw new Error(missingFieldsErrorMessage);
  }

  return {
    requiredToRequired: $requiredToRequired,
    requiredToAsymmetric: $requiredToAsymmetric,
    requiredToOptional: $requiredToOptional,
    asymmetricToRequired: $asymmetricToRequired,
    asymmetricToAsymmetric: $asymmetricToAsymmetric,
    asymmetricToOptional: $asymmetricToOptional,
    optionalToRequired: $optionalToRequired,
    optionalToAsymmetric: $optionalToAsymmetric,
    optionalToOptional: $optionalToOptional,
    nonexistentToAsymmetric: $nonexistentToAsymmetric,
    nonexistentToOptional: $nonexistentToOptional,
  };
}

function exampleStructSerialize(message: ExampleStructOut): ArrayBuffer {
  const atlasValue = exampleStructAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  exampleStructSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function exampleStructDeserialize(bytes: Deserializable): ExampleStructIn | Error {
  try {
    if (bytes instanceof ArrayBuffer) {
      return exampleStructDeserializeUnsafe(new DataView(bytes));
    }
    if (bytes instanceof DataView) {
      return exampleStructDeserializeUnsafe(bytes);
    }
    return exampleStructDeserializeUnsafe(new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength));
  } catch (e) {
    return e as Error;
  }
}

export const ExampleStruct = {
  atlas: exampleStructAtlas,
  size: exampleStructSize,
  serializeWithAtlasUnsafe: exampleStructSerializeWithAtlasUnsafe,
  deserializeUnsafe: exampleStructDeserializeUnsafe,
  serialize: exampleStructSerialize,
  deserialize: exampleStructDeserialize,
};

export type ExampleChoiceAtlas =
  | { $size: number; requiredToRequired: Uint8Array }
  | { $size: number; requiredToAsymmetric: Uint8Array; $fallback: ExampleChoiceAtlas }
  | { $size: number; asymmetricToRequired: Uint8Array }
  | { $size: number; asymmetricToAsymmetric: Uint8Array; $fallback: ExampleChoiceAtlas }
  | { $size: number; asymmetricToOptional: Uint8Array; $fallback: ExampleChoiceAtlas }
  | { $size: number; optionalToRequired: Uint8Array }
  | { $size: number; optionalToAsymmetric: Uint8Array; $fallback: ExampleChoiceAtlas }
  | { $size: number; optionalToOptional: Uint8Array; $fallback: ExampleChoiceAtlas }
  | { $size: number; nonexistentToRequired: number }
  | { $size: number; nonexistentToAsymmetric: number; $fallback: ExampleChoiceAtlas }
  | { $size: number; nonexistentToOptional: number; $fallback: ExampleChoiceAtlas };

export type ExampleChoiceOut =
  | { requiredToRequired: string }
  | { requiredToAsymmetric: string; $fallback: ExampleChoiceOut }
  | { asymmetricToRequired: string }
  | { asymmetricToAsymmetric: string; $fallback: ExampleChoiceOut }
  | { asymmetricToOptional: string; $fallback: ExampleChoiceOut }
  | { optionalToRequired: string }
  | { optionalToAsymmetric: string; $fallback: ExampleChoiceOut }
  | { optionalToOptional: string; $fallback: ExampleChoiceOut }
  | { nonexistentToRequired: null }
  | { nonexistentToAsymmetric: null; $fallback: ExampleChoiceOut }
  | { nonexistentToOptional: null; $fallback: ExampleChoiceOut };

export type ExampleChoiceIn =
  | { $field: 'requiredToRequired'; requiredToRequired: string }
  | { $field: 'requiredToAsymmetric'; requiredToAsymmetric: string }
  | { $field: 'asymmetricToRequired'; asymmetricToRequired: string }
  | { $field: 'asymmetricToAsymmetric'; asymmetricToAsymmetric: string }
  | { $field: 'asymmetricToOptional'; asymmetricToOptional: string; $fallback: ExampleChoiceIn }
  | { $field: 'optionalToRequired'; optionalToRequired: string }
  | { $field: 'optionalToAsymmetric'; optionalToAsymmetric: string }
  | { $field: 'optionalToOptional'; optionalToOptional: string; $fallback: ExampleChoiceIn }
  | { $field: 'nonexistentToRequired'; nonexistentToRequired: null }
  | { $field: 'nonexistentToAsymmetric'; nonexistentToAsymmetric: null }
  | { $field: 'nonexistentToOptional'; nonexistentToOptional: null; $fallback: ExampleChoiceIn };

function exampleChoiceAtlas(message: ExampleChoiceOut): ExampleChoiceAtlas {
  if ('requiredToRequired' in message) {
    let payloadAtlas;
    const payload = message.requiredToRequired;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    return { $size: fieldHeaderSize(0n, payloadSize, false) + payloadSize, requiredToRequired: payloadAtlas };
  }

  if ('requiredToAsymmetric' in message) {
    let payloadAtlas;
    const payload = message.requiredToAsymmetric;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(1n, payloadSize, false) + payloadSize + fallbackAtlas.$size, requiredToAsymmetric: payloadAtlas, $fallback: fallbackAtlas };
  }

  if ('asymmetricToRequired' in message) {
    let payloadAtlas;
    const payload = message.asymmetricToRequired;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    return { $size: fieldHeaderSize(4n, payloadSize, false) + payloadSize, asymmetricToRequired: payloadAtlas };
  }

  if ('asymmetricToAsymmetric' in message) {
    let payloadAtlas;
    const payload = message.asymmetricToAsymmetric;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(5n, payloadSize, false) + payloadSize + fallbackAtlas.$size, asymmetricToAsymmetric: payloadAtlas, $fallback: fallbackAtlas };
  }

  if ('asymmetricToOptional' in message) {
    let payloadAtlas;
    const payload = message.asymmetricToOptional;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(6n, payloadSize, false) + payloadSize + fallbackAtlas.$size, asymmetricToOptional: payloadAtlas, $fallback: fallbackAtlas };
  }

  if ('optionalToRequired' in message) {
    let payloadAtlas;
    const payload = message.optionalToRequired;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    return { $size: fieldHeaderSize(8n, payloadSize, false) + payloadSize, optionalToRequired: payloadAtlas };
  }

  if ('optionalToAsymmetric' in message) {
    let payloadAtlas;
    const payload = message.optionalToAsymmetric;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(9n, payloadSize, false) + payloadSize + fallbackAtlas.$size, optionalToAsymmetric: payloadAtlas, $fallback: fallbackAtlas };
  }

  if ('optionalToOptional' in message) {
    let payloadAtlas;
    const payload = message.optionalToOptional;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(10n, payloadSize, false) + payloadSize + fallbackAtlas.$size, optionalToOptional: payloadAtlas, $fallback: fallbackAtlas };
  }

  if ('nonexistentToRequired' in message) {
    let payloadAtlas;
    const payload = message.nonexistentToRequired;
    payloadAtlas = 0;
    const payloadSize = payloadAtlas;
    return { $size: fieldHeaderSize(12n, payloadSize, false) + payloadSize, nonexistentToRequired: payloadAtlas };
  }

  if ('nonexistentToAsymmetric' in message) {
    let payloadAtlas;
    const payload = message.nonexistentToAsymmetric;
    payloadAtlas = 0;
    const payloadSize = payloadAtlas;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(13n, payloadSize, false) + payloadSize + fallbackAtlas.$size, nonexistentToAsymmetric: payloadAtlas, $fallback: fallbackAtlas };
  }

  if ('nonexistentToOptional' in message) {
    let payloadAtlas;
    const payload = message.nonexistentToOptional;
    payloadAtlas = 0;
    const payloadSize = payloadAtlas;
    const fallbackAtlas = exampleChoiceAtlas(message.$fallback);
    return { $size: fieldHeaderSize(14n, payloadSize, false) + payloadSize + fallbackAtlas.$size, nonexistentToOptional: payloadAtlas, $fallback: fallbackAtlas };
  }

  return unreachable(message);
}

function exampleChoiceSize(message: ExampleChoiceOut): number {
  return exampleChoiceAtlas(message).$size;
}

function exampleChoiceSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: ExampleChoiceOut,
  atlas: ExampleChoiceAtlas,
): number {
  if ('requiredToRequired' in message) {
    const payload = message.requiredToRequired;
    const payloadAtlas = (atlas as any).requiredToRequired as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 0n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    return offset;
  }

  if ('requiredToAsymmetric' in message) {
    const payload = message.requiredToAsymmetric;
    const payloadAtlas = (atlas as any).requiredToAsymmetric as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 1n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  if ('asymmetricToRequired' in message) {
    const payload = message.asymmetricToRequired;
    const payloadAtlas = (atlas as any).asymmetricToRequired as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 4n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    return offset;
  }

  if ('asymmetricToAsymmetric' in message) {
    const payload = message.asymmetricToAsymmetric;
    const payloadAtlas = (atlas as any).asymmetricToAsymmetric as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 5n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  if ('asymmetricToOptional' in message) {
    const payload = message.asymmetricToOptional;
    const payloadAtlas = (atlas as any).asymmetricToOptional as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 6n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  if ('optionalToRequired' in message) {
    const payload = message.optionalToRequired;
    const payloadAtlas = (atlas as any).optionalToRequired as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 8n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    return offset;
  }

  if ('optionalToAsymmetric' in message) {
    const payload = message.optionalToAsymmetric;
    const payloadAtlas = (atlas as any).optionalToAsymmetric as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 9n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  if ('optionalToOptional' in message) {
    const payload = message.optionalToOptional;
    const payloadAtlas = (atlas as any).optionalToOptional as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 10n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  if ('nonexistentToRequired' in message) {
    const payload = message.nonexistentToRequired;
    const payloadAtlas = (atlas as any).nonexistentToRequired as number;
    const payloadSize = payloadAtlas;
    offset = serializeFieldHeader(dataView, offset, 12n, payloadSize, false);
    return offset;
  }

  if ('nonexistentToAsymmetric' in message) {
    const payload = message.nonexistentToAsymmetric;
    const payloadAtlas = (atlas as any).nonexistentToAsymmetric as number;
    const payloadSize = payloadAtlas;
    offset = serializeFieldHeader(dataView, offset, 13n, payloadSize, false);
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  if ('nonexistentToOptional' in message) {
    const payload = message.nonexistentToOptional;
    const payloadAtlas = (atlas as any).nonexistentToOptional as number;
    const payloadSize = payloadAtlas;
    offset = serializeFieldHeader(dataView, offset, 14n, payloadSize, false);
    offset = exampleChoiceSerializeWithAtlasUnsafe(dataView, offset, message.$fallback, (atlas as any).$fallback as ExampleChoiceAtlas);
    return offset;
  }

  return unreachable(message);
}

function exampleChoiceDeserializeUnsafe(dataView: DataView): ExampleChoiceIn {
  const dataViewAlias = dataView;

  let offset = 0;

  while (true) {
    const [newOffset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    offset = newOffset;

    switch (index) {
      case 0n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'requiredToRequired',
          requiredToRequired: payload,
        };
      }
      case 1n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'requiredToAsymmetric',
          requiredToAsymmetric: payload,
        };
      }
      case 4n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'asymmetricToRequired',
          asymmetricToRequired: payload,
        };
      }
      case 5n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'asymmetricToAsymmetric',
          asymmetricToAsymmetric: payload,
        };
      }
      case 6n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        const $fallback = exampleChoiceDeserializeUnsafe(
          new DataView(
            dataViewAlias.buffer,
            dataViewAlias.byteOffset + offset,
            dataViewAlias.byteLength - offset,
          ),
        );
        return {
          $field: 'asymmetricToOptional',
          asymmetricToOptional: payload,
          $fallback,
        };
      }
      case 8n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'optionalToRequired',
          optionalToRequired: payload,
        };
      }
      case 9n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'optionalToAsymmetric',
          optionalToAsymmetric: payload,
        };
      }
      case 10n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new Uint8Array(
            dataView.buffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        const $fallback = exampleChoiceDeserializeUnsafe(
          new DataView(
            dataViewAlias.buffer,
            dataViewAlias.byteOffset + offset,
            dataViewAlias.byteLength - offset,
          ),
        );
        return {
          $field: 'optionalToOptional',
          optionalToOptional: payload,
          $fallback,
        };
      }
      case 12n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = null;
        return {
          $field: 'nonexistentToRequired',
          nonexistentToRequired: payload,
        };
      }
      case 13n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = null;
        return {
          $field: 'nonexistentToAsymmetric',
          nonexistentToAsymmetric: payload,
        };
      }
      case 14n: {
        const dataView = new DataView(
          dataViewAlias.buffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = null;
        offset += oldOffset;
        const $fallback = exampleChoiceDeserializeUnsafe(
          new DataView(
            dataViewAlias.buffer,
            dataViewAlias.byteOffset + offset,
            dataViewAlias.byteLength - offset,
          ),
        );
        return {
          $field: 'nonexistentToOptional',
          nonexistentToOptional: payload,
          $fallback,
        };
      }
      default:
        offset += payloadSize;
        break;
    }
  }
}

function exampleChoiceSerialize(message: ExampleChoiceOut): ArrayBuffer {
  const atlasValue = exampleChoiceAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  exampleChoiceSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function exampleChoiceDeserialize(bytes: Deserializable): ExampleChoiceIn | Error {
  try {
    if (bytes instanceof ArrayBuffer) {
      return exampleChoiceDeserializeUnsafe(new DataView(bytes));
    }
    if (bytes instanceof DataView) {
      return exampleChoiceDeserializeUnsafe(bytes);
    }
    return exampleChoiceDeserializeUnsafe(new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength));
  } catch (e) {
    return e as Error;
  }
}

export const ExampleChoice = {
  atlas: exampleChoiceAtlas,
  size: exampleChoiceSize,
  serializeWithAtlasUnsafe: exampleChoiceSerializeWithAtlasUnsafe,
  deserializeUnsafe: exampleChoiceDeserializeUnsafe,
  serialize: exampleChoiceSerialize,
  deserialize: exampleChoiceDeserialize,
};
