// This file was automatically generated by Typical 0.0.0.
// Visit https://github.com/stepchowfun/typical for more information.

/* eslint-disable */

import {
  Deserializable,
  dataViewFromDeserializable,
  deserializeFieldHeader,
  deserializeVarint,
  fieldHeaderSize,
  missingFieldsErrorMessage,
  serializeFieldHeader,
  serializeVarint,
  textDecoder,
  textEncoder,
  unreachable,
  varintSizeFromValue,
  zigzagDecode,
  zigzagEncode,
} from '../common';

import * as _After from './after';
import * as _Before from './before';

export type SingletonStructAtlas = {
  $size: number;
  x: Uint8Array;
};

export type SingletonStructOut = {
  x: string;
};

export type SingletonStructIn = {
  x: string;
};

function singletonStructAtlas(message: SingletonStructOut): SingletonStructAtlas {
  let size = 0;

  let $x: Uint8Array;

  {
    let payloadAtlas: Uint8Array;
    const payload = message.x;
    payloadAtlas = textEncoder.encode(payload);
    $x = payloadAtlas;
    const payloadSize = payloadAtlas.byteLength;
    size += fieldHeaderSize(0n, payloadSize, false) + payloadSize;
  }

  return {
    $size: size,
    x: $x,
  };
}

function singletonStructSize(message: SingletonStructOut): number {
  return singletonStructAtlas(message).$size;
}

function singletonStructSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: SingletonStructOut,
  atlas: SingletonStructAtlas,
): number {
  {
    const payload = message.x;
    const payloadAtlas = atlas.x;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 0n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer as ArrayBuffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
  }

  return offset;
}

function singletonStructDeserializeUnsafe(dataView: DataView): SingletonStructIn {
  const dataViewAlias = dataView;

  let offset = 0;

  let $x: string | undefined;

  while (true) {
    let index: bigint;
    let payloadSize: number;

    try {
      [offset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    } catch (e) {
      if (e instanceof RangeError) {
        break;
      } else {
        throw e;
      }
    }

    switch (index) {
      case 0n: {
        const dataView = new DataView(
          dataViewAlias.buffer as ArrayBuffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new DataView(
            dataView.buffer as ArrayBuffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        offset += oldOffset;
        $x = payload;
        break;
      }
      default:
        offset += payloadSize;
        break;
    }
  }

  if ($x === undefined) {
    throw new Error(missingFieldsErrorMessage);
  }

  return {
    x: $x,
  };
}

function singletonStructSerialize(message: SingletonStructOut): ArrayBuffer {
  const atlasValue = singletonStructAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  singletonStructSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function singletonStructDeserialize(bytes: Deserializable): SingletonStructIn | Error {
  try {
    return singletonStructDeserializeUnsafe(dataViewFromDeserializable(bytes));
  } catch (e) {
    return e as Error;
  }
}

export const SingletonStruct = {
  atlas: singletonStructAtlas,
  size: singletonStructSize,
  serializeWithAtlasUnsafe: singletonStructSerializeWithAtlasUnsafe,
  deserializeUnsafe: singletonStructDeserializeUnsafe,
  serialize: singletonStructSerialize,
  deserialize: singletonStructDeserialize,
};

export type SingletonChoiceAtlas =
  | { $size: number; x: Uint8Array };

export type SingletonChoiceOut =
  | { x: string };

export type SingletonChoiceIn =
  | { $field: 'x'; x: string }
  | { $field: never };

function singletonChoiceAtlas(message: SingletonChoiceOut): SingletonChoiceAtlas {
  if ('x' in message) {
    let payloadAtlas: Uint8Array;
    const payload = message.x;
    payloadAtlas = textEncoder.encode(payload);
    const payloadSize = payloadAtlas.byteLength;
    return { $size: fieldHeaderSize(0n, payloadSize, false) + payloadSize, x: payloadAtlas };
  }

  return unreachable(message);
}

function singletonChoiceSize(message: SingletonChoiceOut): number {
  return singletonChoiceAtlas(message).$size;
}

function singletonChoiceSerializeWithAtlasUnsafe(
  dataView: DataView,
  offset: number,
  message: SingletonChoiceOut,
  atlas: SingletonChoiceAtlas,
): number {
  if ('x' in message) {
    const payload = message.x;
    const payloadAtlas = (atlas as any).x as Uint8Array;
    const payloadSize = payloadAtlas.byteLength;
    offset = serializeFieldHeader(dataView, offset, 0n, payloadSize, false);
    {
      const targetBuffer = new Uint8Array(
        dataView.buffer as ArrayBuffer,
        dataView.byteOffset,
        dataView.byteLength,
      );
      targetBuffer.set(payloadAtlas, offset);
      offset += payloadAtlas.byteLength;
    }
    return offset;
  }

  return unreachable(message);
}

function singletonChoiceDeserializeUnsafe(dataView: DataView): SingletonChoiceIn {
  const dataViewAlias = dataView;

  let offset = 0;

  while (true) {
    const [newOffset, index, payloadSize] = deserializeFieldHeader(dataViewAlias, offset);
    offset = newOffset;

    switch (index) {
      case 0n: {
        const dataView = new DataView(
          dataViewAlias.buffer as ArrayBuffer,
          dataViewAlias.byteOffset + offset,
          payloadSize,
        );
        const oldOffset = offset;
        offset = 0;
        let payload = textDecoder.decode(
          new DataView(
            dataView.buffer as ArrayBuffer,
            dataView.byteOffset + offset,
            dataView.byteLength - offset,
          ),
        );
        offset = dataView.byteLength;
        return {
          $field: 'x',
          x: payload,
        };
      }
      default:
        offset += payloadSize;
        break;
    }
  }
}

function singletonChoiceSerialize(message: SingletonChoiceOut): ArrayBuffer {
  const atlasValue = singletonChoiceAtlas(message);
  const arrayBuffer = new ArrayBuffer(atlasValue.$size);
  const dataView = new DataView(arrayBuffer);
  singletonChoiceSerializeWithAtlasUnsafe(dataView, 0, message, atlasValue);
  return arrayBuffer;
}

function singletonChoiceDeserialize(bytes: Deserializable): SingletonChoiceIn | Error {
  try {
    return singletonChoiceDeserializeUnsafe(dataViewFromDeserializable(bytes));
  } catch (e) {
    return e as Error;
  }
}

export const SingletonChoice = {
  atlas: singletonChoiceAtlas,
  size: singletonChoiceSize,
  serializeWithAtlasUnsafe: singletonChoiceSerializeWithAtlasUnsafe,
  deserializeUnsafe: singletonChoiceDeserializeUnsafe,
  serialize: singletonChoiceSerialize,
  deserialize: singletonChoiceDeserialize,
};
